version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:80" # Maps container port 3000 to host port 3000
    volumes:
      - .:/usr/src/app # Mounts the current directory to the working directory in the container
      - /usr/src/app/node_modules # Prevents overwriting node_modules in the container
    environment:
      NODE_ENV: development
volumes:
  db-data: # Creates a named volume for persisting the database data
