version: "3.9"

services:
  app:
    image: 654654475781.dkr.ecr.eu-west-1.amazonaws.com/memora-api:${IMAGE_TAG}
    ports:
      - 8091:80
    dns: 169.254.169.253
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10m
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
